> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Hello There


### My Five Functions

More or less a beginner in using the Numpy library. Here are five functions I had fun playing around with.

- stack
- split
- reshape
- copyto
- diag

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='python-assignment2')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "nanamo1/python-assignment2" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/nanamo1/python-assignment2


'https://jovian.ml/nanamo1/python-assignment2'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [5]:
# List of functions explained 
function1 = np.stack  # (change this)
function2 = np.split
function3 = np.reshape
function4 = np.copyto
function5 = np.diag

SyntaxError: invalid syntax (<ipython-input-5-af752533b49a>, line 4)

## Function 1 - np.stack

The stack functions made a 3D array by combining the two input arrays in axis 0.

In [6]:
# Example 1 - working (change this)
arr1 = [[2, 7, 8], 
        [3, 4., 1]]

arr2 = [[5, 6, 9], 
        [8, 3, 10]]

np.stack((arr1, arr2), axis=0)

array([[[ 2.,  7.,  8.],
        [ 3.,  4.,  1.]],

       [[ 5.,  6.,  9.],
        [ 8.,  3., 10.]]])

Now, the function made a 3D array by taking the columns (axis=1) of the input arrays and joined the sequences along the axis=2.

In [7]:
# Example 2 - working
arr1 = np.eye(3)

arr2 = np.ones((3, 3)) * 3

np.stack((arr1, arr2), axis=2)

array([[[1., 3.],
        [0., 3.],
        [0., 3.]],

       [[0., 3.],
        [1., 3.],
        [0., 3.]],

       [[0., 3.],
        [0., 3.],
        [1., 3.]]])

Lets try different shaped arrays.

In [8]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.stack((arr1, arr2), axis=0)

ValueError: all input arrays must have the same shape

There is an error because the function was unable to join an equal number of sequences from the two input arrays because they were different shapes. Make sure to have them the same and to have the (max axis + 1) as highest for axis argument.

Some closing comments about when to use this function.

In [9]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "nanamo1/python-assignment2" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/nanamo1/python-assignment2


'https://jovian.ml/nanamo1/python-assignment2'

## Function 2 - np.split

The split function took the 2D array with shape (4, 3) and returned a 3D array with shapes (2, 3) by split along deflaut axis=0

In [10]:
# Example 1 - working
arr1 = np.array([[3, 4, 5],
                 [10, 4, 6],
                 [9, 5, 2],
                 [1, 6, 7]])

np.split(arr1, 2)

[array([[ 3,  4,  5],
        [10,  4,  6]]),
 array([[9, 5, 2],
        [1, 6, 7]])]

A list of three arrays of shape (2, 1) were returned from an input array of shape (2, 3) splitting from axis=1

In [11]:
# Example 2 - working
arr1 = np.array([[4, 8, 10],
                 [11, 2, 9]])

np.split(arr1, 3, axis=1)

[array([[ 4],
        [11]]),
 array([[8],
        [2]]),
 array([[10],
        [ 9]])]

Let's try spliting the array from axis=1

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([[3, 4, 5, 6],
                 [10, 4, 6, 9],
                 [9, 5, 2, 3]])

np.split(arr1, 3, axis=1)

ValueError: array split does not result in an equal division

The example breaks because the input array cannot be split into 3 from axis=1 as there is four coloumns/sequences in that axis.

Some closing comments about when to use this function.

In [13]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "nanamo1/python-assignment2" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/nanamo1/python-assignment2


'https://jovian.ml/nanamo1/python-assignment2'

## Function 3 - np.reshape

The function takes an array and reshapes it according to the specified shape of (1, 8) or just 8.

In [36]:
# Example 1 - working
arr1 = [[2, 7, 8, 4], 
        [3, 4, 1, 9]]

np.reshape(arr1, 8)

array([2, 7, 8, 4, 3, 4, 1, 9])

A 3D arrray of 3 units in axis=2 was created from shape (3, 4) to (3, 4, 1).

In [38]:
# Example 2 - working
arr1 = [[3, 4, 5, 6],
        [10, 4, 6, 9],
        [9, 5, 2, 3]]

np.reshape(arr1, (3, 4, 1))

array([[[ 3],
        [ 4],
        [ 5],
        [ 6]],

       [[10],
        [ 4],
        [ 6],
        [ 9]],

       [[ 9],
        [ 5],
        [ 2],
        [ 3]]])

Explanation about example

In [42]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[5, 9 ,10, 4, 8, 2],
        [3, 5, 1, 7, 2, 9]]

np.reshape(arr1, (2,3))

ValueError: cannot reshape array of size 12 into shape (2,3)

There was an error as the new shape was inappropriate for the original array to be rearrange into because where all elements in the original needs to be in the new array.

Some closing comments about when to use this function.

In [44]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "nanamo1/python-assignment2" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/nanamo1/python-assignment2


'https://jovian.ml/nanamo1/python-assignment2'

## Function 4 - np.copyto

The copyto function pastes the values into an array from another array from they were copied from. The arguments are taken respectively. 

In [5]:
# Example 1 - working
arr1 = np.array([[3, 9, 2, 7],
                 [4, 6, 1, 3]])

arr2 = np.array([[4, 3, 2, 1],
                 [1, 2 ,3, 4]])

np.copyto(arr1, arr2)
arr1

array([[4, 3, 2, 1],
       [1, 2, 3, 4]])

The function can also broadcast as necessary. Here, the single element in array 2 was replicated to fit the shape of (4, 4), and then copied into arr1.

In [6]:
# Example 2 - working
arr1 = np.array([[7, 4, 2, 5],
                 [6, 4, 5, 10],
                 [1, 2, 9, 1],
                 [3, 8, 7, 4]])

arr2 = np.array([5, 4, 3, 2, 1])
np.copyto(arr1, arr2)
arr1

ValueError: could not broadcast input array from shape (5) into shape (4,4)

Let try something different with the same 4X4 matrix.

In [7]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([2, 2])

arr2 = np.array([[7, 4, 2, 5],
                 [6, 4, 5, 10],
                 [1, 2, 9, 1],
                 [3, 8, 7, 4]])

np.copyto(arr2, arr1)
arr1

ValueError: could not broadcast input array from shape (2) into shape (4,4)

The example broke as arr1 was unable to broadcast into shape (4, 4) from (2, 2) as the array cannot be replicated from more than one direction/axis. 

Some closing comments about when to use this function.

In [19]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "nanamo1/python-assignment2" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/nanamo1/python-assignment2


'https://jovian.ml/nanamo1/python-assignment2'

## Function 5 - np.det

The linalg det function returns an the determinant on a given array.

In [11]:
# Example 1 - working
arr1 = np.array([[7, 4, 2, 5],
                 [6, 4, 5, 1],
                 [1, 2, 9, 1],
                 [3, 4, 8, 7]])

np.linalg.det(arr1)

239.99999999999997

Another example that is simpler.

In [15]:
# Example 2 - working
arr1 = np.array([[1, 2.], 
                 [3, 4]])

np.linalg.det(arr1)

-2.0000000000000004

What about when not working with a N x N array?

In [16]:
# Example 3 - breaking (to illustrate when it breaks)

arr1 = np.matrix([[7, 4, 2, 5],
                 [6, 4, 5, 10],
                 [1, 2, 9, 1]])

np.linalg.det(arr1)

LinAlgError: Last 2 dimensions of the array must be square

The determinant can never be caluclated unless a square array or matrix is given. 

Some closing comments about when to use this function.

In [17]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "nanamo1/python-assignment2" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/nanamo1/python-assignment2


'https://jovian.ml/nanamo1/python-assignment2'

## Conclusion

So we went through the stack, split, reshape, copyto, and determinant functions from the python library called numpy. 4 of them were manipulating arrays and one of from the linear algebra module. 

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
